module.exports={
    loading:false,
    userProfile:{
        name:'',
        photo:'',
    },
    popUp:{
        show:false,
        header:{
            text:[]
        },
        body:{
            text:[]
        },
        footer:{
            text:[],
            button:{
                name:[],
                onClickHandlers:[],
            }
        }
    }
}